export const TEMPLATE_ADD = 'TEMPLATE_ADD';
export const TEMPLATE_FETCH_STARTED = 'TEMPLATE_FETCH_STARTED';
export const TEMPLATE_FETCH_COMPLETED = 'TEMPLATE_FETCH_COMPLETED';
export const TEMPLATE_FETCH_ERROR = 'TEMPLATE_FETCH_ERROR';
export const TEMPLATE_STORE_STARTED = 'TEMPLATE_STORE_STARTED';
export const TEMPLATE_STORE_COMPLETED = 'TEMPLATE_STORE_COMPLETED';
export const TEMPLATE_STORE_ERROR = 'TEMPLATE_STORE_ERROR';
export const TEMPLATE_UPDATE_STARTED = 'TEMPLATE_UPDATE_STARTED';
export const TEMPLATE_UPDATE_COMPLETED = 'TEMPLATE_UPDATE_COMPLETED';
export const TEMPLATE_UPDATE_ERROR = 'TEMPLATE_UPDATE_ERROR';


export const LIST_ADD = 'LIST_ADD';
export const LIST_UPDATE = 'LIST_UPDATE';
export const LIST_FETCH_STARTED = 'LIST_FETCH_STARTED';
export const LIST_FETCH_COMPLETED = 'LIST_FETCH_COMPLETED';
export const LIST_FETCH_ERROR = 'LIST_FETCH_ERROR';

export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_COMPLETED = 'LOGIN_COMPLETED';
export const LOGIN_ERROR = 'LOGIN_ERROR';