export const TEMPLATE_ADD = 'TEMPLATE_ADD';
export const TEMPLATE_UPDATE = 'TEMPLATE_UPDATE';
export const TEMPLATE_FETCH_STARTED = 'TEMPLATE_FETCH_STARTED';
export const TEMPLATE_FETCH_COMPLETED = 'TEMPLATE_FETCH_COMPLETED';
export const TEMPLATE_FETCH_ERROR = 'TEMPLATE_FETCH_ERROR';

export const LIST_ADD = 'LIST_ADD';